Repository morph-l2/morph, pull requests merged in 2024-09, with the labels that each got.

#506 add retryable error
  node/types/retryable_client.go
Labels: release/0.2.x

#508 error handling
  node/types/retryable_client.go
Labels: release/0.2.x

#513 Make every eth call from node to geth retryable
  node/core/batch.go
  node/core/executor.go
  node/core/sequencers.go
  node/types/retryable_client.go
Labels: release/0.2.x

#517 Clean oracle config
  oracle/config/config.go
  oracle/flags/flags.go
  oracle/oracle/oracle.go
Labels: release/0.2.x

#519 Fix config validate and clean eks
  MakefileEks.mk
  oracle/config/config.go
Labels: release/0.2.x

#521 Fix ValidateConfig
  oracle/config/config.go
Labels: release/0.2.x

#526 Enable parsing log level for different modules
  node/core/config.go
  node/sequencer/tm_node.go
Labels: release/0.2.x

#499 Fix oracle docker-compose.yml
  oracle/docker-compose.yml
Labels: release/0.2.x

#529 Event listen rotator
  ops/docker/docker-compose-4nodes.yml
  tx-submitter/entry.go
  tx-submitter/event/indexer.go
  tx-submitter/event/storage.go
  tx-submitter/event/storage_test.go
  tx-submitter/flags/flags.go
  tx-submitter/iface/rollup.go
  tx-submitter/metrics/metrics.go
  tx-submitter/services/rollup.go
  tx-submitter/services/rotator.go
  tx-submitter/utils/config.go
  tx-submitter/utils/methods.go
Labels: tx-submitter, release/0.2.x

#532 Event listen rotator
  ops/docker/docker-compose-4nodes.yml
Labels: release/0.2.x

#555 Cleaning up expired variables
  bindings/bin/gov_deployed.hex
  bindings/bindings/gov.go
  bindings/bindings/gov_more.go
  contracts/contracts/l2/staking/Gov.sol
  contracts/contracts/l2/staking/IGov.sol
  contracts/contracts/test/Gov.t.sol
  contracts/contracts/test/base/L2StakingBase.t.sol
Labels: contracts
