Repository morph-l2/morph, pull requests merged in 2024-08, with the labels that each got.

#449 Run full node in docker container with one command
  ops/publicnode/.env
  ops/publicnode/Dockerfile.geth-nccc
  ops/publicnode/Dockerfile.node
  ops/publicnode/Makefile
  ops/publicnode/docker-compose.yml
  ops/publicnode/holesky/entrypoint-geth.sh
  ops/publicnode/holesky/geth-data/static-nodes.json
  ops/publicnode/holesky/node-data/config/config.toml
  ops/publicnode/holesky/node-data/config/genesis.json
  ops/publicnode/holesky/node-data/data/.gitignore
Labels: release/0.2.x

#452 update submodule before run node
  ops/publicnode/Makefile
Labels: release/0.2.x

#447 Fix audit issue
  bindings/bin/distribute_deployed.hex
  bindings/bin/l2staking_deployed.hex
  bindings/bin/morphtoken_deployed.hex
  bindings/bindings/distribute.go
  bindings/bindings/distribute_more.go
  bindings/bindings/l2staking.go
  bindings/bindings/l2staking_more.go
  bindings/bindings/morphtoken.go
  bindings/bindings/morphtoken_more.go
  contracts/contracts/l2/staking/Distribute.sol
  contracts/contracts/l2/staking/IDistribute.sol
  contracts/contracts/l2/staking/L2Staking.sol
  contracts/contracts/l2/system/MorphToken.sol
  contracts/contracts/test/L2Staking.t.sol
Labels: release/0.2.x

#457 Fix oracle findStartBlock
  oracle/oracle/reward.go
Labels: release/0.2.x

#460 blob scalar from origin_batch
  gas-oracle/app/src/da_scalar/blob.rs
  gas-oracle/app/src/da_scalar/calculate.rs
Labels: release/0.2.x

#456 Add support for externalsign
  go.work.sum
  tx-submitter/entry.go
  tx-submitter/flags/flags.go
  tx-submitter/go.mod
  tx-submitter/go.sum
  tx-submitter/services/rollup.go
  tx-submitter/services/sign.go
  tx-submitter/utils/config.go
  tx-submitter/utils/methods.go
Labels: tx-submitter, go, release/0.2.x

#468 upgrade tendermint to v0.2.2-beta
  Makefile
  bindings/go.mod
  bindings/go.sum
  contracts/go.mod
  go.work.sum
  node/go.mod
  node/go.sum
  ops/l2-genesis/go.mod
  ops/l2-genesis/go.sum
  ops/tools/go.mod
  ops/tools/go.sum
  oracle/go.mod
  oracle/go.sum
  tx-submitter/go.mod
  tx-submitter/go.sum
Labels: release/0.2.x

#454 Update contracts
  bindings/bin/distribute_deployed.hex
  bindings/bin/l1staking_deployed.hex
  bindings/bin/morphtoken_deployed.hex
  bindings/bin/rollup_deployed.hex
  bindings/bindings/distribute.go
  bindings/bindings/distribute_more.go
  bindings/bindings/l1staking.go
  bindings/bindings/l1staking_more.go
  bindings/bindings/morphtoken.go
  bindings/bindings/morphtoken_more.go
  bindings/bindings/rollup.go
  bindings/bindings/rollup_more.go
  contracts/contracts/l1/rollup/Rollup.sol
  contracts/contracts/l1/staking/IL1Staking.sol
  contracts/contracts/l1/staking/L1Staking.sol
  contracts/contracts/l2/staking/Distribute.sol
  contracts/contracts/l2/system/MorphToken.sol
  contracts/contracts/test/L1Staking.t.sol
  contracts/contracts/test/Rollup.t.sol
  contracts/contracts/test/base/L1MessageBase.t.sol
Labels: contracts

#466 Add rotator interval buffer for rollup
  tx-submitter/entry.go
  tx-submitter/flags/flags.go
  tx-submitter/services/rollup.go
  tx-submitter/utils/config.go
Labels: tx-submitter, go, release/0.2.x

#475 Add query functions for L2Staking and Distribute contracts
  bindings/bin/distribute_deployed.hex
  bindings/bin/l2staking_deployed.hex
  bindings/bindings/distribute.go
  bindings/bindings/distribute_more.go
  bindings/bindings/l2staking.go
  bindings/bindings/l2staking_more.go
  contracts/contracts/l2/staking/Distribute.sol
  contracts/contracts/l2/staking/IDistribute.sol
  contracts/contracts/l2/staking/IL2Staking.sol
  contracts/contracts/l2/staking/L2Staking.sol
  contracts/contracts/test/L2Staking.t.sol
Labels: contracts

#476 Fix oracle set start block
  oracle/oracle/reward.go
  oracle/oracle/types.go
Labels: release/0.2.x

#479 Add limit of max batch count
  oracle/oracle/batch.go
  oracle/oracle/types.go
Labels: release/0.2.x

#482 external sign & gas buffer
  gas-oracle/.env.dev
  gas-oracle/app/Cargo.lock
  gas-oracle/app/Cargo.toml
  gas-oracle/app/src/da_scalar/calculate.rs
  gas-oracle/app/src/da_scalar/l1_scalar.rs
  gas-oracle/app/src/external_sign.rs
  gas-oracle/app/src/gas_price_oracle.rs
  gas-oracle/app/src/l1_base_fee.rs
  gas-oracle/app/src/lib.rs
  gas-oracle/app/src/metrics.rs
  gas-oracle/app/src/signer.rs
  gas-oracle/hardhat.config.js
  prover/challenge-handler/Cargo.lock
  prover/challenge-handler/Cargo.toml
  prover/challenge-handler/src/external_sign.rs
  prover/challenge-handler/src/handler.rs
  prover/challenge-handler/src/lib.rs
  prover/challenge-handler/src/util.rs
Labels: release/0.2.x

#480 Add querys
  bindings/bin/distribute_deployed.hex
  bindings/bin/l1gatewayrouter_deployed.hex
  bindings/bin/l1staking_deployed.hex
  bindings/bindings/distribute.go
  bindings/bindings/distribute_more.go
  bindings/bindings/l1gatewayrouter.go
  bindings/bindings/l1gatewayrouter_more.go
  bindings/bindings/l1staking.go
  bindings/bindings/l1staking_more.go
  contracts/contracts/l1/staking/IL1Staking.sol
  contracts/contracts/l1/staking/L1Staking.sol
  contracts/contracts/l2/staking/Distribute.sol
  contracts/contracts/l2/staking/IDistribute.sol
Labels: contracts

#484 Fix clean staker store & clean after claim withdrawal
  bindings/bin/l1staking_deployed.hex
  bindings/bindings/l1staking.go
  bindings/bindings/l1staking_more.go
  contracts/contracts/l1/staking/L1Staking.sol
Labels: contracts, audit_issue_fix

#492 update gasOracle buffer
  gas-oracle/app/src/da_scalar/l1_scalar.rs
  gas-oracle/app/src/gas_price_oracle.rs
  gas-oracle/app/src/lib.rs
  gas-oracle/app/src/signer.rs
  prover/challenge-handler/src/handler.rs
  prover/challenge-handler/src/lib.rs
  prover/shadow-proving/src/shadow_rollup.rs
Labels: release/0.2.x

#491 Oracle add external sign
  oracle/config/config.go
  oracle/flags/flags.go
  oracle/go.mod
  oracle/go.sum
  oracle/oracle/batch.go
  oracle/oracle/oracle.go
  oracle/oracle/reward.go
  oracle/oracle/rollup.go
  oracle/oracle/sign.go
Labels: release/0.2.x

#497 Make priv flag optional
  tx-submitter/flags/flags.go
Labels: tx-submitter, release/0.2.x
